### ISSUE TITLE
I can't install in the webui or even load after downloaded manually

### ISSUE THREAD

**Issue by anhvuhoang2390** [imrayya/stable-diffusion-webui-Prompt_Generator#14]
As the title said, I can't install in the Extension tab. The error says:

Error executing callback ui_tabs_callback for E:\AI_RND\stable-diffusion-webui-master\extensions\stable-diffusion-webui-Prompt_Generator-master\scripts\prompt_generator.py
Traceback (most recent call last):
  File "E:\AI_RND\stable-diffusion-webui-master\modules\script_callbacks.py", line 103, in ui_tabs_callback
    res += c.callback() or []
  File "E:\AI_RND\stable-diffusion-webui-master\extensions\stable-diffusion-webui-Prompt_Generator-master\scripts\prompt_generator.py", line 160, in on_ui_tabs
    populate_models()
  File "E:\AI_RND\stable-diffusion-webui-master\extensions\stable-diffusion-webui-Prompt_Generator-master\scripts\prompt_generator.py", line 34, in populate_models
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './extensions/stable-diffusion-webui-Prompt_Generator/models.json'

Even when I manually downloaded the git and extracted to extension folder, the A1111 still got error.

**Comment by anhvuhoang2390** [comment]
I realized a tips to solve: delete the word "-master" in the end of the folder "stable-diffusion-webui-Prompt_Generator-master"

**Comment by imrayya** [comment]
So it no longer an issue for you?

Either way, I think I need to make it more robust for future people installing

**Comment by anhvuhoang2390** [comment]
Yes. I've already solved the problem. Thanks. But I think we should keep this question here for other people.
