### ISSUE TITLE
Error: stderr: 'fatal: repository '0.9' does not exist

### ISSUE THREAD

**Issue by GeneralAwareness** [imrayya/stable-diffusion-webui-Prompt_Generator#22]
Error completing request
Arguments: ('sliced cheese', '0.9') {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-ux\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui-ux\modules\ui_extensions.py", line 153, in install_extension_from_url
    with git.Repo.clone_from(url, tmpdir) as repo:
  File "D:\stable-diffusion-webui-ux\venv\lib\site-packages\git\repo\base.py", line 1308, in clone_from
    return cls._clone(
  File "D:\stable-diffusion-webui-ux\venv\lib\site-packages\git\repo\base.py", line 1219, in _clone
    finalize_process(proc, stderr=stderr)
  File "D:\stable-diffusion-webui-ux\venv\lib\site-packages\git\util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "D:\stable-diffusion-webui-ux\venv\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- 0.9 D:\stable-diffusion-webui-ux\tmp\sliced cheese
  stderr: 'fatal: repository '0.9' does not exist

**Comment by imrayya** [comment]
Can you tell me what you were trying to do when this error happened?
Were you trying to install it?

**Comment by GeneralAwareness** [comment]
No, it installed just fine I was simply trying to gen an image.

**Comment by imrayya** [comment]
The trace back shows a Git issue.

I'd delete the extension folder and reinstall it. It seems like something went wrong when installing the extension. Since the traceback shows that none of the extension's code hasn't been ran. Hope that helps

**Comment by GeneralAwareness** [comment]
Works now.  Thank you.

As to seeing any of that, I only saw what I posted with the ticket.
